from pathlib import Path
import shutil

from tools.code_generator import create_code_generator


SAMPLE_DEVELOPER_OUTPUT = """
## 1. Implementation Summary

Sample generated project.

## 3. Generated Files

### File: backend/app.js

FILE_CONTENTS_START
const express = require("express");

const app = express();

app.get("/", (req, res) => {
    res.json({ message: "CodeForge generated project" });
});

module.exports = app;
FILE_CONTENTS_END

### File: backend/package.json

FILE_CONTENTS_START
{
    "name": "sample-project",
    "version": "1.0.0",
    "main": "app.js"
}
FILE_CONTENTS_END

### File: README.md

FILE_CONTENTS_START
# Sample Project

Generated by CodeForge AI.
FILE_CONTENTS_END
"""


def main():
    print("=" * 70)
    print("CODEFORGE AI - CODE GENERATOR TEST")
    print("=" * 70)

    output_root = "outputs"

    project_name = "test-generated-project"

    project_path = Path(output_root) / project_name

    # Remove previous test output.
    if project_path.exists():
        shutil.rmtree(project_path)

    generator = create_code_generator(
        output_root=output_root
    )

    print("\nParsing Developer Agent output...")

    files = generator.parse_files(
        SAMPLE_DEVELOPER_OUTPUT
    )

    assert len(files) == 3

    assert "backend/app.js" in files
    assert "backend/package.json" in files
    assert "README.md" in files

    print("✅ File parsing passed")

    print("\nWriting generated project...")

    result = generator.generate_project(
        project_name=project_name,
        developer_output=SAMPLE_DEVELOPER_OUTPUT,
    )

    assert result["file_count"] == 3

    generated_root = Path(
        result["project_path"]
    )

    assert (
        generated_root / "backend" / "app.js"
    ).exists()

    assert (
        generated_root / "backend" / "package.json"
    ).exists()

    assert (
        generated_root / "README.md"
    ).exists()

    print("✅ Project directory creation passed")
    print("✅ File creation passed")

    # Verify actual contents.
    app_content = (
        generated_root / "backend" / "app.js"
    ).read_text(encoding="utf-8")

    assert "express" in app_content
    assert "CodeForge generated project" in app_content

    print("✅ File content validation passed")

    # Security test.
    malicious_output = """
### File: ../../evil.txt

FILE_CONTENTS_START
malicious content
FILE_CONTENTS_END
"""

    try:
        generator.parse_files(malicious_output)
        raise AssertionError(
            "Path traversal was not rejected."
        )
    except ValueError:
        print("✅ Path traversal protection passed")

    print("\n" + "=" * 70)
    print("✅ CODE GENERATOR TEST PASSED")
    print("=" * 70)


if __name__ == "__main__":
    main()