from pathlib import Path
import shutil
import zipfile

from services.generation_service import create_generation_service


SAMPLE_DEVELOPER_OUTPUT = """
## 3. Generated Files

### File: backend/app.js

FILE_CONTENTS_START
const express = require("express");

const app = express();

app.get("/", (req, res) => {
    res.json({ message: "CodeForge AI generated project" });
});

module.exports = app;
FILE_CONTENTS_END

### File: backend/package.json

FILE_CONTENTS_START
{
    "name": "codeforge-demo",
    "version": "1.0.0",
    "main": "app.js"
}
FILE_CONTENTS_END

### File: README.md

FILE_CONTENTS_START
# CodeForge AI Generated Project

This project was generated by CodeForge AI.
FILE_CONTENTS_END
"""


def main():
    print("=" * 70)
    print("CODEFORGE AI - GENERATION SERVICE TEST")
    print("=" * 70)

    project_name = "test-generation-service"

    project_path = (
        Path("outputs") / project_name
    )

    zip_path = (
        Path("outputs") / f"{project_name}.zip"
    )

    # Clean previous test output.
    if project_path.exists():
        shutil.rmtree(project_path)

    if zip_path.exists():
        zip_path.unlink()

    service = create_generation_service(
        output_root="outputs"
    )

    print("\nGenerating project...")

    result = service.generate_project(
        project_name=project_name,
        developer_output=SAMPLE_DEVELOPER_OUTPUT,
    )

    print("✅ Project generation completed")

    assert result["project_name"] == project_name
    assert result["file_count"] == 3

    print("✅ File count validation passed")

    generated_root = Path(
        result["project_path"]
    )

    assert (
        generated_root / "backend" / "app.js"
    ).exists()

    assert (
        generated_root / "backend" / "package.json"
    ).exists()

    assert (
        generated_root / "README.md"
    ).exists()

    print("✅ Generated files validation passed")

    generated_zip = Path(
        result["zip_path"]
    )

    assert generated_zip.exists()
    assert generated_zip.stat().st_size > 0

    print("✅ ZIP creation validation passed")

    print("\nChecking ZIP contents...")

    with zipfile.ZipFile(
        generated_zip,
        "r",
    ) as archive:

        names = archive.namelist()

    assert any(
        name.endswith("backend/app.js")
        for name in names
    )

    assert any(
        name.endswith("backend/package.json")
        for name in names
    )

    assert any(
        name.endswith("README.md")
        for name in names
    )

    print("✅ ZIP contents validation passed")

    print("\n" + "=" * 70)
    print("✅ GENERATION SERVICE TEST PASSED")
    print("=" * 70)


if __name__ == "__main__":
    main()